const stepConfig = {
  "Cybersecurity audience": {
    Create: [
      "Presentation",
      "Video",
      "Technical guide",
      "Awareness material",
      "Project documentation",
      "Web page",
      "Comms",
    ],
    Publish: [
      "Presentation",
      "Video",
      "Technical guide",
      "Awareness material",
      "Project documentation",
      "Web page",
      "Event page",
      "Comms",
    ],
    "Collaborate on": [
      "Co-authored document",
      "Files that don't require team-wide access",
      "My team's documents and internal sites management",
      "Procedures across the team, wikis, internal long-term project documentation",
      "Documents exchanged with third parties or secure confidential internal information",
      "Documents and information in accordance with HSBC information classification policies",
      "Microsoft 365 files shared with HSBC colleagues in private and public sides of the bank",
      "Translations",
      "Projects",
    ],
    Communicate: [
      "A message with global audience",
      "Video",
      "Technical guide",
      "Meetings and webinars",
      "Awareness materials",
      "Comms",
    ],
    Share: [
      "Survey",
      "Video",
      "Q&A and/or polls live",
      "Informal surveys and polls",
      "Large files",
      "Team's files",
      "Files with third parties",
      "Various files using Microsoft 365",
    ],
    Engage: [
      "External, social media & speaker licensing",
      "Town hall",
      "Leadership storytelling",
      "Technical guide",
      "Awareness material",
      "Web page",
    ],
  },
  "Bank internal audience": {
    Create: [
      "Presentation",
      "Video",
      "Technical guide",
      "Awareness material",
      "Project documentation",
      "Web page",
      "Comms",
    ],
    Publish: [
      "Presentation",
      "Video",
      "Technical guide",
      "Awareness material",
      "Project documentation",
      "Web page",
      "Event page",
      "Comms",
    ],
    "Collaborate on": [
      "Co-authored document",
      "Files that don't require team-wide access",
      "My team's documents and internal sites management",
      "Procedures across the team, wikis, internal long-term project documentation",
      "Documents exchanged with third parties or secure confidential internal information",
      "Documents and information in accordance with HSBC information classification policies",
      "Microsoft 365 files shared with HSBC colleagues in private and public sides of the bank",
      "Translations",
      "Projects",
    ],
    Communicate: [
      "A message with global audience",
      "Video",
      "Technical guide",
      "Meetings and webinars",
      "Awareness materials",
      "Comms",
    ],
    Share: [
      "Survey",
      "Video",
      "Q&A and/or polls live",
      "Informal surveys and polls",
      "Large files",
      "Team's files",
      "Files with third parties",
      "Various files using Microsoft 365",
    ],
    Engage: [
      "External, social media & speaker licensing",
      "Town hall",
      "Leadership storytelling",
      "Technical guide",
      "Awareness material",
      "Web page",
    ],
  },
};
